from enum import Enum

class ResponseSignal(Enum):
    
    FILE_IS_VALID = "FILE_IS_VALID"
    FILE_TYPE_IS_NOT_SUPPORTED = "FILE_TYPE_IS_NOT_SUPPORTED"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    FILE_UPLOAD_SUCCESSFUL = "FILE_UPLOAD_SUCCESSFUL"
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"